# Generated by Django 3.2.3 on 2021-06-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_post_announcement_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=1, null=True, verbose_name='Статус публикации статьи'),
        ),
    ]
